#Docker-compose file for alphanet infra
# Run it using: $ docker-compose up

version: "3"
services:
  marklogic:
    image: marklogic:8.05-installed
    networks:
      - marklogic_network
    restart: always
    environment:
      MYSQL_PASSWORD: cdc
    ports:
      - 8001:8001
      - 8000:8000
      - 8002:8002
networks:
  marklogic_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.28.0/24
